feat: notion db loader
hwchase17/langchainjs pull request #1342
Opened 2023-05-20 05:58 UTC by munkhorgil

WIP

2023-05-24 00:46 UTC, munkhorgil commented
Hey @jacoblee93, this one should be good to go.

2023-05-24 01:44 UTC, jacoblee93 commented
Thank you! Will take a look as soon as I can.

2023-05-24 17:42 UTC, jacoblee93 commented on docs/docs/modules/indexes/document_loaders/examples/web_loaders/notiondb.md
> +---
Can you change this to an `.mdx` file and move the example code to the `examples/` directory? 

https://github.com/hwchase17/langchainjs/blob/main/.github/contributing/INTEGRATIONS.md

2023-05-24 17:43 UTC, jacoblee93 commented on langchain/src/document_loaders/web/notiondb.ts
> +    if (!integrationToken) {
Would be nice to try to load this from an environment variable like `process.env.NOTION_INTEGRATION_TOKEN`:

https://github.com/hwchase17/langchainjs/pull/1396/files#diff-e709c029fd4e48f9d3c541ae2399d64278cfe86491d525cd2e9d9f146281f3a8R33

2023-05-24 17:44 UTC, jacoblee93 commented on langchain/src/document_loaders/web/notiondb.ts
> +      "Notion-Version": "2022-06-28",
Can we make this version string passable as well?

2023-05-24 17:45 UTC, jacoblee93 commented on langchain/src/document_loaders/web/notiondb.ts
> +    while (hasMore) {
Maybe some configurable limit here?

2023-05-24 17:46 UTC, jacoblee93 requested changes
Looks great overall - would love to see an integration test if possible as I'm sure this will be a popular one!

2023-05-25 22:45 UTC, jacoblee93 approved these changes

2023-05-25 22:46 UTC, jacoblee93 commented
Thank you! Will merge with the next release.

2023-05-26 01:55 UTC, munkhorgil commented
> Thank you! Will merge with the next release.

Thanks for the fixes!

2023-05-26 19:35 UTC, merged