feat: Created Upstash Redis Chat Memory for Edge and Serverless environments
hwchase17/langchainjs pull request #1346
Opened 2023-05-20 23:56 UTC by henriquegdantas

**Hello!**

This is my first contribution, so if there's something that needs to be changed, I'm open to suggestions.

It's based on the Redis Chat Memory, but the upstash client uses HTTP instead of a TCP connection, which allows us to use this on **Edge and Serverless environments**.

This was an important feature to me so I hope it helps other people.
I added docs and tests, too.

Thanks for the awesome work on langchain.

2023-05-22 23:31 UTC, jacoblee93 requested changes

2023-05-22 23:31 UTC, jacoblee93 commented on langchain/.env.example
> +REDIS_UPUPSTASH_REDIS_REST_TOKENSTASH_TOKEN=ADD_YOURS_HERE
Bad find and replace looks like?

2023-05-22 23:31 UTC, jacoblee93 commented on langchain/scripts/create-entrypoints.js
> +  "stores/message/redis_upstash": "stores/message/redis_upstash",
Can we reverse the order of all these names to `upstash_redis` to mirror the company's name?

2023-05-22 23:31 UTC, jacoblee93 commented
Looks good, just a few small comments!

2023-05-24 22:38 UTC, jacoblee93 commented
Some polish and `s/upstash_redis/redis_upstash` to better match Upstash's language. 

Thank you very much, this will help a lot of people in serverless environments!

2023-05-24 23:22 UTC, jacoblee93 approved these changes

2023-05-24 23:30 UTC, merged

2023-05-25 22:32 UTC, henriquegdantas commented
> Some polish and `s/upstash_redis/redis_upstash` to better match Upstash's language.
> 
> Thank you very much, this will help a lot of people in serverless environments!

Sorry for not replying earlier. Had a super busy week.
Thanks for the fixes! Glad I could help.