Add blockchain document loader integration
hwchase17/langchainjs pull request #1704
Opened 2023-06-19 23:14 UTC by zuketo

Hello! To mirror the blockchain data document loader in the Python LangChain project, I've created a blockchain data document loader for LangChain.js that utilizes the sort.xyz free API (and includes more functionality).

The document loader includes three types of blockchain data requests:
- Latest transactions for an Ethereum, Polygon, or Ethereum Testnet (Goerli) contract
- Metadata for an NFT
- Arbitrary SQL created by the user for querying blockchain data and using the result in a document

We have a number of tutorials planned for how to use LangChain.js with the new blockchain document loader in this PR.

This PR includes a great set of examples (with all three requests types above), tests, and docs. I believe this PR is ready for review.

Please respond with any feedback. We're excited to get this PR into the community and start work on tutorials and documentation to further expand on use cases!

2023-06-29 01:26 UTC, jacoblee93 requested changes

2023-06-29 01:26 UTC, jacoblee93 commented on examples/src/document_loaders/blockchain.ts
> +import { BlockchainPagesLoader } from 'langchain/document_loaders/web/blockchain';
Can we call this something different since it uses a third-party? Maybe `SortBlockchainLoader`?

2023-06-29 01:26 UTC, jacoblee93 commented on examples/src/document_loaders/blockchain.ts
> +  const apiKey = 'dd46a0ae-5a1a-4c6f-8328-46618c4a73d4';
Replace with something more obviously fake

2023-06-29 01:26 UTC, jacoblee93 commented on langchain/src/document_loaders/web/blockchain.ts
> +    while (true) {
Check for limit changes in the while loop condition rather than a constant here

2023-06-29 01:26 UTC, jacoblee93 commented
Thanks! Left a few comments

2023-07-10 18:43 UTC, jacoblee93 commented
Hey @zuketo, it was almost there and I couldn't push to the `sortxyz` repo directly, so I opened #1918 and will merge this in that PR. Thank you for the hard work and patience! Will plan to get it out in tomorrow's release.

2023-07-10 19:34 UTC, zuketo commented
Hey @jacoblee93 thanks for your help here with the PR! I got one of your feedback items addressed but got sidetracked before fixing the other suggestions, I rather use your PR now, thanks again!

2023-07-12 05:27 UTC, jacoblee93 commented
Merged with #1918!

2023-07-12 05:27 UTC, closed without merging