Add Searxng Search wrapper as built-in tool
hwchase17/langchainjs pull request #1839
Opened 2023-07-02 10:26 UTC by iamrony777

feat(searxng_search.ts): add new tool `SearxngSearch` to perform search using the Searxng API

The `SearxngSearch` tool is added to perform meta search engine queries using the Searxng API. This tool is useful for answering questions about current events. The input should be a search query, and the output is a JSON array of the query results.

The `SearxngSearch` tool includes the following features:
- Support for specifying the number of results included in the output
- Support for specifying the active search categories and engines
- Support for specifying the language, search page number, and time range of search
- Support for specifying the output format of results
- Support for opening search results on a new tab and proxying image results through SearXNG
- Support for autocomplete and safe search filtering

The `SearxngSearch` tool requires the following environment variable to be set:
- `SEARXNG_API_BASE`: Base URL of the Searxng instance

The `SearxngSearch` tool can be instantiated with custom parameters and headers. If using a self-hosted instance, no custom headers are needed.

The `_call` method of the `SearxngSearch` tool performs the actual API call to the Searxng instance. It sends a POST request to the search endpoint with the specified query and parameters. The response is parsed and processed to extract the relevant information from the query results, answers, infoboxes, and suggestions.

If no good results are found, the method returns the message "No good results found." If query results are found, the method returns a JSON array of the results. If answers are found, the method returns the first answer. If infoboxes are found, the method returns the content of the first infobox without HTML tags. If suggestions are found, the method returns a string with the suggestions.

2023-07-04 15:25 UTC, iamrony777 commented
Hope it gets merged soon.

2023-07-07 13:55 UTC, iamrony777 commented
Can someone merge this?

2023-07-10 19:13 UTC, jacoblee93 commented on examples/src/tools/searxng_search.ts
> +  // Works best with  `agentType: "structured-chat-zero-shot-react-description"`
Let's remove this comment - a new agent could come out.

2023-07-10 19:14 UTC, jacoblee93 commented on langchain/src/tools/searxng_search.ts
> +  format?: "json" | "csv" | "rss";
Let's just fix this to `"json"` and not make it configurable?

2023-07-10 19:14 UTC, jacoblee93 commented on langchain/src/tools/searxng_search.ts
> +  num_results?: number;
Prefer camel case in JS rather than snake case

2023-07-10 19:16 UTC, jacoblee93 requested changes
Looks good, a few small comments!

Can you also add this tool here?

https://js.langchain.com/docs/modules/agents/tools/integrations/

2023-07-13 20:01 UTC, jacoblee93 approved these changes

2023-07-14 01:09 UTC, merged