UnstructuredLoader: add timeout option
hwchase17/langchainjs pull request #1869
Opened 2023-07-05 14:29 UTC by thundo

Fixes #1856 

Adds a per-request timeout option to the `UnstructuredLoader`, allowing a timeout different from 5 minutes to be passed to the constructor.

2023-07-06 23:42 UTC, jacoblee93 requested changes
Thanks for submitting this - would really like to avoid adding an additional dependency. Can we do this in base fetch?

2023-07-06 23:42 UTC, jacoblee93 commented on langchain/package.json
> +    "undici": "^5.22.1",
Can we do this without the additional dependency?

2023-07-07 08:26 UTC, thundo commented
> Thanks for submitting this - would really like to avoid adding an additional dependency. Can we do this in base fetch?

Not that I'm aware of. Since Node18 node `fetch` is internally implemented with `undici` (mantained more or less by the same node core team) and for the dispatcher you need to instantiate at least an `Agent`, which is an exported `undici` class.

See this [discussion](https://github.com/nodejs/undici/issues/1373) for reference.

2023-07-07 13:50 UTC, jacoblee93 commented
Unfortunately in this case we need to support more than Nodr (Edge functions, CF Workers, Deno).

2023-07-07 14:20 UTC, thundo commented
> Unfortunately in this case we need to support more than Nodr (Edge functions, CF Workers, Deno).

Totally missed the portability concerns... I'll scout about it and report back.

2023-07-07 14:24 UTC, closed without merging